### ISSUE TITLE
Animation flickering on android

### ISSUE THREAD

**Issue by kkortes** [micahrye/react-native-animated-sprite#1]
Hello there! Love this repo!

I have a problem with my animations on android phone. The first "loop" through the animation every image flickers until one iteration is made, after that the animation runs smoothly as intended.

I was thinking mabye it's because the frames (.png's) are loaded when the view is prompted and it is trying to "catch up" with the animation. Doing a preload and/or cache for the images might be a solution. Do you have any thoughts on this issue? (the .pngs are already optimized)

(only android)

**Comment by naltimari** [comment]
I've had the same issue, however my animation flickers all the time. I'm using Tweens as well.

**Comment by micahrye** [comment]
There are potentially a few issues. First, there will be a flicker on the "first" loading of the image. Basically, the frame rate is faster than the loading of the images into active memory, for this reason you get the flicker, but after initial load the flicker will go away. 

Typically, I will load all images during scene loading, i.e. I will have a load screen and behind that I am loading the images and playing through animations to make sure all images are in active memory. 

Now, there are cases that you can have flickers even after the first load. This is typically a case that there are to many things in memory, so Android/IOS are moving data to disk and back to active memory. 

In general, you have to be careful with how many images and the size of images you are using because mobile devices have limited memory. This is especially true with older devices. 

Hope that helps.

**Comment by micahrye** [comment]
Sorry for the slow reply too.
